.PHONY: clean All

All:
	@echo "----------Building project:[ carpetCleaningQuote - Debug ]----------"
	@cd "carpetCleaningQuote" && "$(MAKE)" -f  "carpetCleaningQuote.mk"
clean:
	@echo "----------Cleaning project:[ carpetCleaningQuote - Debug ]----------"
	@cd "carpetCleaningQuote" && "$(MAKE)" -f  "carpetCleaningQuote.mk" clean
