.PHONY: clean All

All:
	@echo "----------Building project:[ favoriteNumber - Debug ]----------"
	@cd "favoriteNumber" && "$(MAKE)" -f  "favoriteNumber.mk"
clean:
	@echo "----------Cleaning project:[ favoriteNumber - Debug ]----------"
	@cd "favoriteNumber" && "$(MAKE)" -f  "favoriteNumber.mk" clean
